# Generated by Django 6.0 on 2025-12-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
